import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.util.*;

/**
 *
 * @author jick
 */
public class interfaz extends javax.swing.JFrame 
{
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Align_Center;
    private javax.swing.JButton Align_left;
    private javax.swing.JButton Aling_right;
    private javax.swing.JMenu Doble;
    private javax.swing.JLabel Height;
    private javax.swing.JLabel Imagen;
    private javax.swing.JMenu Options;
    private javax.swing.JMenu Reset;
    private javax.swing.JButton Resize;
    private javax.swing.JTextField T_Heigh;
    private javax.swing.JTextField T_width;
    private javax.swing.JLabel Width;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form interfaz
     */
    public interfaz() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() 
    {
        //Declaracion de datos.
        Align_left = new javax.swing.JButton();
        Align_Center = new javax.swing.JButton();
        Aling_right = new javax.swing.JButton();
        Resize = new javax.swing.JButton();
        Height = new javax.swing.JLabel();
        Width = new javax.swing.JLabel();
        T_width = new javax.swing.JTextField();
        T_Heigh = new javax.swing.JTextField();
        Imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Options = new javax.swing.JMenu();
        Reset = new javax.swing.JMenu();
        Doble = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        //Declaracion de titulos
        setTitle("Image Application");
        Align_left.setText("Align Left");
        Align_Center.setText("Align Center");
        Resize.setText("Resize");
        Aling_right.setText("Align Right");
        Height.setText("Height:");
        Width.setText("Width:");
        Options.setText("Options");
        Reset.setText("Reset");
        Doble.setText("Double");
        
        //Lamadas al producirse un evento
        Align_Center.addActionListener(new java.awt.event.ActionListener() 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {
                Align_CenterActionPerformed(evt);
            }
        });
        
        //left
        Align_left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Align_leftMouseClicked(evt);
            }
        });
        
        //center
         Align_Center.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Align_CenterMouseClicked(evt);
            }
        });
        
        //right
            Aling_right.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Aling_rightMouseClicked(evt);
            }
        });

        
         Align_Center.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Align_CenterMouseClicked(evt);
            }
        });
        
        Resize.addMouseListener(new java.awt.event.MouseAdapter() 
        {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResizeMouseClicked(evt);
            }
        });
        
        Resize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResizeActionPerformed(evt);
            }
        });

        

        Imagen.setIcon(new javax.swing.ImageIcon("/home/jick/NetBeansProjects/display/img/7171716078_cd1c0aa390_m.jpg")); // NOI18N


       
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });
        Options.add(Reset);

        
        Doble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DobleMouseClicked(evt);
            }
        });
        Options.add(Doble);

        jMenuBar1.add(Options);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Height)
                            .addComponent(Width))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(T_Heigh)
                            .addComponent(T_width)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Resize, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Align_left, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Align_Center, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(Aling_right, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Imagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Align_left, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(Aling_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Align_Center, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Width))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_Heigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Height))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Resize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Resolucion de eventos
    private void Align_CenterActionPerformed(java.awt.event.ActionEvent evt) {}
    
    private void DobleMouseClicked(java.awt.event.MouseEvent evt) 
    {//GEN-FIRST:event_DobleMouseClicked
        
        Imagen.setSize(200,200);
        Toolkit tk=Toolkit.getDefaultToolkit();
        Image i=tk.createImage("/home/jick/NetBeansProjects/display/img/7171716078_cd1c0aa390_m.jpg");
        Imagen.setIcon(new ImageIcon(i.getScaledInstance(Imagen.getWidth()*2, Imagen.getHeight()*2,i.SCALE_AREA_AVERAGING)));
        Imagen.setSize(457,317);
    }//GEN-LAST:event_DobleMouseClicked

    private void ResizeMouseClicked(java.awt.event.MouseEvent evt) 
    {//GEN-FIRST:event_ResizeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ResizeMouseClicked
    
    private void ResizeActionPerformed(java.awt.event.ActionEvent evt) 
    {                                       

        try
        {
            int w_=Integer.parseInt(T_width.getText());
            int h_=Integer.parseInt(T_Heigh.getText());
            Imagen.setSize(200,200);
            Toolkit tk=Toolkit.getDefaultToolkit();
            Image i=tk.createImage("/home/jick/NetBeansProjects/display/img/7171716078_cd1c0aa390_m.jpg");
            Imagen.setIcon(new ImageIcon(i.getScaledInstance(w_,h_,i.SCALE_AREA_AVERAGING)));
            
        }
        catch (NumberFormatException eFormatoNumero ) 
        {
             System.out.println("Invalid format");
        }
        
            
        
        Imagen.setSize(457,317);
        
        
    }   
    
      private void ResetMouseClicked(java.awt.event.MouseEvent evt) {                                   

        Imagen.setIcon(new javax.swing.ImageIcon("/home/jick/NetBeansProjects/display/img/7171716078_cd1c0aa390_m.jpg"));
        Imagen.setSize(457,317);
        Imagen.setHorizontalAlignment(JLabel.LEFT);
        //Imagen.setVerticalAlignment(JLabel.LEFT);
        
    }                              
    
    private void Align_CenterMouseClicked(java.awt.event.MouseEvent evt) 
    {//GEN-FIRST:event_Align_CenterMouseClicked
                   
        Imagen.setHorizontalAlignment(JLabel.CENTER);
    }//GEN-LAST:event_Align_CenterMouseClicked

    private void Align_leftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Align_leftMouseClicked
       Imagen.setHorizontalAlignment(JLabel.LEFT);
    }//GEN-LAST:event_Align_leftMouseClicked

    private void Aling_rightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Aling_rightMouseClicked
        Imagen.setHorizontalAlignment(JLabel.RIGHT);
    }//GEN-LAST:event_Aling_rightMouseClicked


}
