package game;


import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jick
 */
public class intefaz extends javax.swing.JFrame {

    /**
     * Creates new form intefaz
     */
    public intefaz() 
    {
        mov=0;
        d=new data();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        j0_0 = new javax.swing.JLabel();
        j0_1 = new javax.swing.JLabel();
        j0_2 = new javax.swing.JLabel();
        j1_0 = new javax.swing.JLabel();
        j1_1 = new javax.swing.JLabel();
        j1_2 = new javax.swing.JLabel();
        j2_0 = new javax.swing.JLabel();
        j2_1 = new javax.swing.JLabel();
        j2_2 = new javax.swing.JLabel();
        new_game = new javax.swing.JButton();
        Moves = new javax.swing.JLabel();
        count = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Message");

        jPanel2.setBackground(new java.awt.Color(15, 2, 4));

        j0_0.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        j0_0.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        j0_0.setForeground(new java.awt.Color(255, 250, 250));
        j0_0.setText("          1");
        j0_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 4));
        j0_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j0_0MouseClicked(evt);
            }
        });

        j0_1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        j0_1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        j0_1.setForeground(new java.awt.Color(255, 250, 250));
        j0_1.setText("          2");
        j0_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 4));
        j0_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j0_1MouseClicked(evt);
            }
        });

        j0_2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        j0_2.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        j0_2.setForeground(new java.awt.Color(255, 250, 250));
        j0_2.setText("          3");
        j0_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 4));
        j0_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j0_2MouseClicked(evt);
            }
        });

        j1_0.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        j1_0.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        j1_0.setForeground(new java.awt.Color(255, 250, 250));
        j1_0.setText("          4");
        j1_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 4));
        j1_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1_0MouseClicked(evt);
            }
        });

        j1_1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        j1_1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        j1_1.setForeground(new java.awt.Color(255, 250, 250));
        j1_1.setText("          5");
        j1_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 4));
        j1_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1_1MouseClicked(evt);
            }
        });

        j1_2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        j1_2.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        j1_2.setForeground(new java.awt.Color(255, 250, 250));
        j1_2.setText("          6");
        j1_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 4));
        j1_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1_2MouseClicked(evt);
            }
        });

        j2_0.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        j2_0.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        j2_0.setForeground(new java.awt.Color(255, 250, 250));
        j2_0.setText("          7");
        j2_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 4));
        j2_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2_0MouseClicked(evt);
            }
        });

        j2_1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        j2_1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        j2_1.setForeground(new java.awt.Color(255, 250, 250));
        j2_1.setText("          8");
        j2_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 4));
        j2_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2_1MouseClicked(evt);
            }
        });

        j2_2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        j2_2.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        j2_2.setForeground(new java.awt.Color(255, 250, 250));
        j2_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 4));
        j2_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2_2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(j2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(j0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(j1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(j1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        new_game.setText("NEW GAME");
        new_game.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_gameMouseClicked(evt);
            }
        });
        new_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_gameActionPerformed(evt);
            }
        });

        Moves.setText("  Moves");
        Moves.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        count.setText("   0");
        count.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(new_game, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(Moves, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(new_game, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Moves, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_gameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_gameActionPerformed
 /**jlabel funcion (i, j)
         if (i==0 && j==0)
    **/    
         
    private void new_gameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_gameMouseClicked
        
        for(int i=0; i<3; i++)
        {
            for(int j=0; j<3; j++)
            {
                if(i==0 && j==0)
                {
                    if(d.getNumber(i,j)!=0)
                    {
                        j0_0.setText(String.valueOf(d.getNumber(i,j)));
                        
                    }
                    else
                    {
                        j0_0.setText(" ");
                        k=i;
                        l=j;
                        
                    }
                    j0_0.setHorizontalAlignment(JLabel.CENTER);
                    
                }
                    
                if(i==0 && j==1)
                {
                    if(d.getNumber(i,j)!=0) 
                    {
                        j0_1.setText(String.valueOf(d.getNumber(i,j)));
                    }
                    else
                    {
                        j0_1.setText(" ");
                         k=i;
                         l=j;
                    }
                  j0_1.setHorizontalAlignment(JLabel.CENTER);
                }
                    
                if(i==0 && j==2)
                {
                    if(d.getNumber(i,j)!=0)
                    {
                        j0_2.setText(String.valueOf(d.getNumber(i,j)));
                         
                    }
                      else
                    {
                        j0_2.setText(" ");
                        k=i;
                        l=j;
                    }
                  j0_2.setHorizontalAlignment(JLabel.CENTER);
                }
                    
                if(i==1 && j==0)
                {
                    if(d.getNumber(i,j)!=0)
                    {
                        j1_0.setText(String.valueOf(d.getNumber(i,j)));
                       
                    }
                      else
                    {
                        j1_0.setText(" ");
                        k=i;
                        l=j;
                    }
                    j1_0.setHorizontalAlignment(JLabel.CENTER);
                }
                    
                if(i==1 && j==1)
                {
                    if(d.getNumber(i,j)!=0)
                    {
                        j1_1.setText(String.valueOf(d.getNumber(i,j)));
                    }
                      else
                    {
                        j1_1.setText(" ");
                        k=i;
                        l=j;
                    }
                    j1_1.setHorizontalAlignment(JLabel.CENTER);
                }
                    
                if(i==1 && j==2)
                {
                    if(d.getNumber(i,j)!=0)
                    {
                        j1_2.setText(String.valueOf(d.getNumber(i,j)));
                    }
                    else
                    {
                        j1_2.setText(" ");
                        k=i;
                        l=j;
                    }
                    j1_2.setHorizontalAlignment(JLabel.CENTER);
                }
                    
                if(i==2 && j==0)
                {
                    if(d.getNumber(i,j)!=0)
                    {
                        j2_0.setText(String.valueOf(d.getNumber(i,j)));
                        
                    }
                    else
                    {
                        j2_0.setText(" ");
                         k=i;
                         l=j;
                    }
                  j2_0.setHorizontalAlignment(JLabel.CENTER);
                }
                
                if(i==2 && j==1)
                {
                    if(d.getNumber(i,j)!=0)
                    {
                        j2_1.setText(String.valueOf(d.getNumber(i,j)));
                    }
                    else
                    {
                        j2_1.setText(" ");
                        k=i;
                        l=j;
                    }
                  j2_1.setHorizontalAlignment(JLabel.CENTER);
                }
                            
                if(i==2 && j==2)
                {
                    if(d.getNumber(i,j)!=0)
                    {
                        j2_2.setText(String.valueOf(d.getNumber(i,j)));
                    }
                    else
                    {
                        j2_2.setText(" ");
                        k=i;
                        l=j;
                    }
                  j2_2.setHorizontalAlignment(JLabel.CENTER);
                }
            }
        }
        System.out.println(k+" "+l);
        
    }//GEN-LAST:event_new_gameMouseClicked

    private void j0_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j0_0MouseClicked
        if(d.Move(0,0)==true)
        {
            System.out.println("Movemos 0,0");
            //System.out.println(k+" "+l);
                if(k==0 && l==1)
                {
                    System.out.println("Bandera 0,0 a 0,1");
                    String aux=new String(j0_0.getText());
                    j0_0.setText(j0_1.getText());
                    j0_1.setText(aux);
                    
                }
                    
                   
                if(k==1 && l==0)
                {
                    System.out.println("Bandera 0,0 a 1,0");
                    String aux=new String(j0_0.getText());
                    j0_0.setText(j1_0.getText());
                    j1_0.setText(aux);
                }
                k=0;
                l=0; 
                mov++;
                count.setText(String.valueOf(mov));
                count.setHorizontalAlignment(JLabel.CENTER);
                 if(d.is_end()==true)
                {
                    w.int_dialog();
                }
        
                
        }
    }//GEN-LAST:event_j0_0MouseClicked

    private void j0_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j0_2MouseClicked
        boolean hi;
        if(d.Move(0,2)==true)
        {
            if(k==0 && l==1)
            {
                String aux=new String(j0_2.getText());
                j0_2.setText(j0_1.getText());
                j0_1.setText(aux);
            }
            
            if(k==1 && l==2)
            {
                String aux=new String(j0_2.getText());
                j0_2.setText(j1_2.getText());
                j1_2.setText(aux);
            }
            k=0;
            l=2;
            mov++;
            count.setText(String.valueOf(mov));
            count.setHorizontalAlignment(JLabel.CENTER);
        }
        if(d.is_end()==true)
        {
            w.int_dialog();
        }
    }//GEN-LAST:event_j0_2MouseClicked

    private void j0_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j0_1MouseClicked
        if(d.Move(0,1)==true)
        {
            
            if(k==0 && l==0)
            {
                String aux=new String(j0_1.getText());
                j0_1.setText(j0_0.getText());
                j0_0.setText(aux);
            }
                        
            if(k==0 && l==2)
            {
                String aux=new String(j0_1.getText());
                j0_1.setText(j0_2.getText());
                j0_2.setText(aux);
            }
                    
            if(k==1 && l==1)
            {
                String aux=new String(j0_1.getText());
                j0_1.setText(j1_1.getText());
                j1_1.setText(aux);
            }
         k=0;
         l=1;
         mov++;
         count.setText(String.valueOf(mov));
         count.setHorizontalAlignment(JLabel.CENTER);
        }
        if(d.is_end()==true)
        {
            w.int_dialog();
        }
    }//GEN-LAST:event_j0_1MouseClicked

    private void j1_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1_0MouseClicked
        
        if(d.Move(1,0)==true)
        {
            if(k==0 && l==0)
            {
                String aux=new String(j1_0.getText());
                j1_0.setText(j0_0.getText());
                j0_0.setText(aux);
            }
                        
            if(k==1 && l==1)
            {
                String aux=new String(j1_0.getText());
                j1_0.setText(j1_1.getText());
                j1_1.setText(aux);
            }
                           
            if(k==2 && l==0)
            {
                String aux=new String(j1_0.getText());
                j1_0.setText(j2_0.getText());
                j2_0.setText(aux);
            }
         k=1;
         l=0;
         mov++;
         count.setText(String.valueOf(mov));
         count.setHorizontalAlignment(JLabel.CENTER);
        }
        if(d.is_end()==true)
        {
            w.int_dialog();
        }
    }//GEN-LAST:event_j1_0MouseClicked

    private void j1_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1_1MouseClicked
        if(d.Move(1,1)==true)
        {
            if(k==0 && l==1)
            {
                String aux=new String(j1_1.getText());
                j1_1.setText(j0_1.getText());
                j0_1.setText(aux);
            }
                    
                    
            if(k==1 && l==0)
            {
                String aux=new String(j1_1.getText());
                j1_1.setText(j1_0.getText());
                j1_0.setText(aux);
                    
            }
                       
            if(k==1 && l==2)
            {
                String aux=new String(j1_1.getText());
                j1_1.setText(j1_2.getText());
                j1_2.setText(aux);
            }
                    
            if(k==2 && l==1)
            {
                String aux=new String(j1_1.getText());
                j1_1.setText(j2_1.getText());
                j2_1.setText(aux);
            }
         k=1;
         l=1;
         mov++;
         count.setText(String.valueOf(mov));
         count.setHorizontalAlignment(JLabel.CENTER);
          if(d.is_end()==true)
        {
            w.int_dialog();
        }
        
        }
        
    }//GEN-LAST:event_j1_1MouseClicked

    private void j1_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1_2MouseClicked
         if(d.Move(1,2)==true)
        {
                    
                if(k==0 && l==2)
                {
                    String aux=new String(j1_2.getText());
                j1_2.setText(j0_2.getText());
                j0_2.setText(aux);
                }
                    
                if(k==1 && l==1)
                {
                    String aux=new String(j1_2.getText());
                j1_2.setText(j1_1.getText());
                j1_1.setText(aux);
                }
                            
                if(k==2 && l==2)
                {
                    String aux=new String(j1_2.getText());
                    j1_2.setText(j2_2.getText());
                    j2_2.setText(aux);
                }
         k=1;
         l=2;
         mov++;
         count.setText(String.valueOf(mov));
         count.setHorizontalAlignment(JLabel.CENTER);
         if(d.is_end()==true)
        {
            w.int_dialog();
        }
        
       }
         
    }//GEN-LAST:event_j1_2MouseClicked

    private void j2_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2_0MouseClicked
        if(d.Move(2,0)==true)
        {
                if(k==1 && l==0)
                {
                    String aux=new String(j2_0.getText());
                j2_0.setText(j1_0.getText());
                j1_0.setText(aux);
                }
                
                if(k==2 && l==1)
                {
                    String aux=new String(j2_0.getText());
                j2_0.setText(j2_1.getText());
                j2_1.setText(aux);
                }
        k=2;
        l=0;
        mov++;
        count.setText(String.valueOf(mov));
        count.setHorizontalAlignment(JLabel.CENTER);
         if(d.is_end()==true)
        {
            w.int_dialog();
        }
        
        }
       
            
    }//GEN-LAST:event_j2_0MouseClicked

    private void j2_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2_1MouseClicked
       if(d.Move(2,1)==true)
       {
                    
                if(k==1 && l==1)
                {
                    String aux=new String(j2_1.getText());
                j2_1.setText(j1_1.getText());
                j1_1.setText(aux);
                }
                    
                if(k==2 && l==0)
                {
                    String aux=new String(j2_1.getText());
                j2_1.setText(j2_0.getText());
                j2_0.setText(aux);
                }
                            
                if(k==2 && l==2)
                {
                    String aux=new String(j2_1.getText());
                j2_1.setText(j2_2.getText());
                j2_2.setText(aux);
                }
       k=2;
       l=1;
       mov++;
       count.setText(String.valueOf(mov));
       count.setHorizontalAlignment(JLabel.CENTER);
        if(d.is_end()==true)
        {
            w.int_dialog();
        }
        
       }
     
    }//GEN-LAST:event_j2_1MouseClicked

    private void j2_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2_2MouseClicked
        
        if(d.Move(2,2)==true)
        {
        if(k==1 && l==2)
                {
                    String aux=new String(j2_2.getText());
                j2_2.setText(j1_2.getText());
                j1_2.setText(aux);
                }
                
                if(k==2 && l==1)
                {
                    String aux=new String(j2_2.getText());
                j2_2.setText(j2_1.getText());
                j2_1.setText(aux);
                }
        k=2;
        l=2;
        mov++;
        count.setText(String.valueOf(mov));
        count.setHorizontalAlignment(JLabel.CENTER);
         if(d.is_end()==true)
         {
            w.int_dialog();
         }
        
        }
    
    }//GEN-LAST:event_j2_2MouseClicked

    /**
     * @param args the command line arguments
     *
    
    public void init_dialog()
    {
           java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                win dialog = new win(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
            
           });
      }
    */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        data d=new data();
        //System.out.println("Numero 1: "+d.getNumber(0,0));
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intefaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Moves;
    private javax.swing.JLabel count;
    private javax.swing.JLabel j0_0;
    private javax.swing.JLabel j0_1;
    private javax.swing.JLabel j0_2;
    private javax.swing.JLabel j1_0;
    private javax.swing.JLabel j1_1;
    private javax.swing.JLabel j1_2;
    private javax.swing.JLabel j2_0;
    private javax.swing.JLabel j2_1;
    private javax.swing.JLabel j2_2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton new_game;
    // End of variables declaration//GEN-END:variables
    private data d;
    private int k;//Casilla cero i
    private int l;//Casilla cero j
    private int mov;
    private win w;
}
